#!/bin/bash
# Create a custom configuration file to add the custom header
# shellcheck disable=SC2154

sudo apt-get update
sudo apt-get install nginx -y
# Allow HTTP traffic in the firewall
sudo ufw allow 'Nginx HTTP'
# Create the default index page
echo "Hello World!" > /var/www/html/index.html
# Configure a custom redirection
string="listen 80 default_server;\\n\\tlocation \/redirect_me {\\n\\t\\treturn 301 https:\/\/www.innovateweb.tech\/;\\n\\t}"
sudo sed -i "s/listen 80 default_server;/$string/" /etc/nginx/sites-enabled/default
# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
# Configure custom error handling
string="listen 80 default_server;\\nerror_page 404 \/404.html;\\n\\tlocation = \/404.html {\\n\\t\\troot \/usr\/share\/nginx\/html;\\n\\t\\tinternal;\\n\\t}"
sudo sed -i "s/listen 80 default_server;/$string/" /etc/nginx/sites-enabled/default
# Add a custom header to Nginx responses
string2="http {\\n\\tadd_header X-Served-By \"$HOSTNAME\";"
sudo sed -i "s/http {/$string2/" /etc/nginx/nginx.conf
sudo service nginx restart
