#!/usr/bin/env bash
# Bash script that displays a list of currently running processes
#+ for all users, including those which might not have a TTY
# The options -e and -f are used to list all processes with full format

ps -eo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command
