#!/usr/bin/env bash
# Bash script that :
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays "I hate the kill command" when receiving a SIGTERM signal
# Displays "Y U no love me?!" when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when
#+ Receiving a SIGQUIT or SIGTERM signal
# To kill the process with Signal intrruption Execute the
#+ 100-process_and_pid_file script: ./100-process_and_pid_file
#+ And killing it with ctrl+c.
# To kill the process with Signal termination open two terminal
#+ windows in terminal 0 Execute the 100-process_and_pid_file script:
#+ ./100-process_and_pid_file and in terminal 1 kill it with:
#+ pkill -f 100-process_and_pid_file

echo $$ > /var/run/myscript.pid

terminate()
{
	echo "I hate the kill command"
	rm /var/run/myscript.pid
	exit
}

terminate_script()
{
	rm /var/run/myscript.pid
	exit
}

interrupt()
{
	echo "Y U no love me?!"
	exit
}

trap terminate SIGTERM
trap terminate_script SIGQUIT
trap interrupt SIGINT

while true
do
	echo "To infinity and beyond"
	sleep 2
done
