#!/usr/bin/env bash
# Bash script that displays:
# "To infinity and beyond" indefinitely
# With a sleep 2 in between each iteration
# It also displays "I am invincible!!!" when receiving a SIGTERM signal
# The script will get killed with the script 67-stop_me_if_you_can

trap 'echo "I am invincible!!!"' 15

while true; do
  echo "To infinity and beyond"
  sleep 2
done
