#!/usr/bin/env bash
# A Bash script that displays data from apache log file and
#+ groups visitors by IP and HTTP status code
# The format is like :
#+ OCCURENCE_NUMBER IP HTTP_CODE
# Ordered from the greatest to the lowest number of occurrences

file="apache-access.log"
awk '{count[$1 " " $9]++} END {for (i in count) print count[i], i}' "$file" | sort -nr
