#!/usr/bin/env bash
# Configure Nginx to run as the nginx user and listen on port 8080
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
systemctl reload nginx
